### ISSUE TITLE
Flags for inference (generating summaries) on Gigaword

### ISSUE THREAD

**Issue by akhilkedia** [KaiQiangSong/control-over-copying#1]
Thank you for providing the source code!

The provided trained model (in others.zip) and the default command mentioned in the [README](https://github.com/KaiQiangSong/control-over-copying/blob/master/README.md#i-want-to-generate-summaries), I am unable to get the exact scores mentioned in table 4 of your paper.

This is probably due to some flag not being set correctly. I obtained the below scores by additionally setting the flag `--reranking_method` - 

| Reranker  |  R1 | R2  | RL  | 
|---|---|---|---|
| none  | 38.77  |  20.21 |  36.43 |
| bounded_adaptive_reward | 38.55  | 19.77  |  36.05 |
| bounded_word_reward_0.25  |  38.97 |  20.27 |  36.56 |
| length_norm | 38.98  | 20.37  |  36.57 |

Perhaps the issue is due to the flags `answer_size` and `beam_size`? The default value for both these params is `5`, but the file `settings/test/test.json` mentions both as `10` (but this file is never actually used). 

Can you tell me which flags I need to enable to reproduce the score of Beam+SBWR in Table 4 of your paper?

**Comment by KaiQiangSong** [comment]
> Thank you for providing the source code!
> 
> The provided trained model (in others.zip) and the default command mentioned in the [README](https://github.com/KaiQiangSong/control-over-copying/blob/master/README.md#i-want-to-generate-summaries), I am unable to get the exact scores mentioned in table 4 of your paper.
> 
> This is probably due to some flag not being set correctly. I obtained the below scores by additionally setting the flag `--reranking_method` -
> 
> Reranker	R1	R2	RL
> none	38.77	20.21	36.43
> bounded_adaptive_reward	38.55	19.77	36.05
> bounded_word_reward_0.25	38.97	20.27	36.56
> length_norm	38.98	20.37	36.57
> Perhaps the issue is due to the flags `answer_size` and `beam_size`? The default value for both these params is `5`, but the file `settings/test/test.json` mentions both as `10` (but this file is never actually used).
> 
> Can you tell me which flags I need to enable to reproduce the score of Beam+SBWR in Table 4 of your paper?

Hi, Akhil Kedia
Thanks for your question. This work has been done during my internship at Bosch 2019. Due to the company policy, I couldn't put the SBWR implementation in this repository. You might need to implement it yourself (Not very hard).

You could get the flag of ranking_method using the function name in scorer.py, and here's the link:
https://github.com/KaiQiangSong/control-over-copying/blob/master/searcher/scorer.py

In case that you might need the generated summaries, I put my generated summaries at:
https://github.com/KaiQiangSong/control-over-copying/blob/master/summary_on_gigaword.zip

**Comment by akhilkedia** [comment]
Ah, I see. I will implement SBWR myself, it doesn't seem too difficult.
Thank you!
Closing the issue.
